### ISSUE TITLE
only show 75 most recent 

### ISSUE THREAD

**Issue by oeon** [SLUGIS/incidentSpreadsheet#8]
automatically remove or archive incidents, so only the most current 75 calls are visible

**Comment by bsyu1125** [comment]
Latest commit has that functionality now. Need some more testing and put it on the digital ocean server though, will continue next week.
Gspread doesn't have a delete row function so just shifted rows up depending on how many new rows there are, added new entries, and capped the excel sheet at 75

**Comment by bsyu1125** [comment]
done
